language: python
sudo: required
python:
  - "2.7"
install: |
  sudo apt-get update && \
  sudo apt-get install default-jre-headless && \
  pip install html5validator
script:
  - html5validator --show-warnings
